name: build debug apk

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: sparkfabrik/android-build-action@v1.5.0
      with:
        project-path: android
        output-path: diosic-debug-latest.apk
        fastlane-env: "debug"
    - uses: sparkfabrik/android-build-action@v1.5.0
      with:
        project-path: android
        output-path: diosic-reelase-latest.apk
        fastlane-env: "release"
